### ISSUE TITLE
Oprava ukolu

### ISSUE THREAD

**Issue by nothumbee** [Desjula/chytry-dum#1]
Zadani splneno, super!

Jen drobnost, ze [tady](https://github.com/Desjula/chytry-dum/blob/765e16c352a616446712f053da03b9c4f8f41cc1/src/components/Dashboard/index.jsx#L13) definujes komponentu Lights uvnitr jine komponenty, coz neni best practice.

**Comment by Desjula** [comment]
Přesunula jsem Lights do samostatné komponenty.
